-- messages

local HVHTALK_CHATMESSAGES = {
	"ur literally dog shit at this game!!!!!!",
	"nn dog? nn dog? nn dog? nn dog? nn dog? nn dog? ",
	[["why am i missing so much?!?!?!?!?" no fake angles in 2k23????]],
	"you can buy a better cheat at cheadleware.net",
	"im winning too much bro. change up ur settings so u can beat me!!!!!!!!!",
	"using idiotbox?",
	"is ur nospread and norecoil working???",
	"nice aa retard lmao",
	"DID YOU SEE THAT BACKTRACK RIGHT THERE???",
    "cheadleware.net > your cheat"
}

local TOXICTALK_CHATMESSAGES = {
	"HOLY SHIT YALL ARE HORRIBLE WTF",
	"MY KD IS SO MUCH BETTER THAN YOURS LOOOOOOOL",
	"YOU WANT TO 1V1 KID? ILL SLAP YOU LIKE YOUR MOTHER",
	"EZZZZZZZZZZZZZZZZZ EZZZZZZZZZZZZZ NO CHEADLEWARE NO TALK",
	[["YO WHAT CHEAT IS THAT WHAT CHEAT" CHEADLEWARE.NET ON TOPPPP]],
	"crash! poof! gone! vaporized! destroyed!",
	"lol you literally got owned by a child.",
	"I WILL DOMINATE YOU BECAUSE IM YOUR MASTER, KITTEN...",
	"HAHAHAHHAHAH OWNEDDDDDDDDDDDDDDDDD",
	"FEELS LIKE TACOBOT.TF. IN REALITY, IM JUST BETTER.",
	"HAHAHA YOUR GETTING TRACKED MEGASCATTERBOMB.COM"
}

local BIBLE_CHATMESSAGES = {
	[["Ask and it will be given to you." - Jesus (Matthew 7:7)]],
	[["Faith can move mountains." - Jesus (Matthew 17:20)]],
	[["I am the way, the truth, and the life." - Jesus (John 14:6)]],
	[["Cast your cares on the Lord." - David (Psalm 55:22)]],
	[["Seek and you will find." - Jesus (Matthew 7:7)]],
	[["The Lord is my light and salvation." - David (Psalm 27:1)]],
	[["Love covers a multitude of sins." - Peter (1 Peter 4:8)]],
	[["Do not worry, for I am with you." - Isaiah (Isaiah 41:10)]],
	[["A soft answer turns away wrath." - Solomon (Proverbs 15:1)]],
	[["Trust in the Lord with all your heart." - Solomon (Proverbs 3:5)]],
	[["I can do everything through Him." - Paul (Philippians 4:13)]],
	[["He heals the brokenhearted." - David (Psalm 147:3)]],
	[["The word of God is living and active." - Paul (Hebrews 4:12)]],
	[["Give thanks in all circumstances." - Paul (1 Thessalonians 5:18)]],
	[["The Lord will fight for you." - Moses (Exodus 14:14)]]
}
	
local CHEADLEWARE_CHATMESSAGES = {
    "Cheadleware on top! Buy now on cheadleware.net",
    "she cheadle on my software whilst spy caming on them hoes with screengrab proof visuals",
    "This server has been backdoored by cheadleware. Please be scared I need attention",
    "UKRAINE PIG OWNS YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "Cheadleware merch coming soon!",
    "BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE",
    "Did you know you can buy cheadleware for 40 dollars only? It's lifetime too. It's kinda crazy...",
    "https://i.imgur.com/lIa2bkE.png cheadlware cake looks so good. you want a slice?",
    "cheadleware.net",
    "cheadleware.net cheadleware.net cheadleware.net cheadleware.net cheadleware.net cheadleware.net cheadleware.net"
}

local NEWGEN_CHATMESSAGES = {
    "Skibidi Dop Dop Dop Yes Yes? Skibidi Dopolo Diep Diep?",
    "Sticking Out Your Gyat For The Rizzler, You're So Skibidi, So Fanum Tax.",
    "OH MY GOOWDDDDDDD LOOK AT THAT GYATTTTTTT",
    "PLEASE NO PROTECT ME FROM THE CAMERAMEN THEY ATTACK ME AND FAMILY OF SKIBIDI TOILETS HELP MEEEEEEEEE",
    "SKIBIDI OWNS YOUR SERVER AND GM_BIGCITY. YOU HAVE NO ESCAPE MUAHAHAHAHAHAHHAHAHHAHHAHAHHHAAAAAA",
    "I just wanna be your sigma, Freaking come here, Give me your ohio.",
    "You're not a sigma male like me. You're a fat loser. Escape the matrix with hustlers university 2.0...",
    "That's so fruity uwu",
    "Did it hurt? When you fell out of heaven? Generated by RizzApp.io",
    "ULTIMATE RIZZ LOADING... 5%... 30%... 70%... 99%... ERROR, SKIBIDI TOILET HACKER DETECTED DEFENDING ATTACK!!!",
    "womp womp"
}

local RYANFOURNIER_CHATMESSAGES = {
    "Your server has been backdoored by evil ryan fournier. Changing level to prometheus_berlin_v2...",
    "Evil Ryan Fournier has access to your computer. Your firewall has been jumped. Say goodbye to your files...",
    "IM GONNA PISTOL WHIP THE SHIT OUT OF YOU HAHAHAHAHAHAHAHAHAHAHAH",
    "Students4Trump Sponsors this daily segment of raping garry's mod servers. Please donate to our ORG.",
    "My wife was my first target, this server is my second target. *he grips his gun harder and harder*",
    "Injecting evil_ryan_fournier_backdoor_services_dll_main_application.exe into server code...",
    "RATTED BY EVILRYANFOURNIER! evilryanfournier.com!"
}

local FEMBOY_CHATMESSAGES = {
    "h-hey. I'm a small little femboy. D-do you want to co-orrupt me? I'm a si-ssy femboy.",
    "I'm into tall and big guys so they can hold me and tell me how much of a good boy I am...",
    "p-p-PLEASE MAASTER GI-IIIVE ME MO-RE O-OF THAT *moaning*",
    "I'm my master's little s-slut. He can do whatever he wants to me and my b-b-body...",
    "I have my vibrator set to low as we speak... I-it feels so go-oood",
    "Master here. My helpless little slut here is such a good girl... He always begs for more like a good soul...",
    "Being a submissive little femboy slut feels so good. I like not having rights.",
    "You can p-pinch and twist both of my nipples. They're very sensitive and round.",
    "I remember when I was t-ied up for hours with a dildo pumping into me. My a-ass has never been the same...",
    "I'm the #385923th cumdump in the world. You can use me for free uwu.",
    "P-Please DM me on discord. My name is 'iamleigh_'. E-Dating Prices are 5-10€ an hour.",
	"P-P-please... master~ m-my b-belly is... hurting... mfgdfm~ p-plea-ah~",
    "M-M-master told m-me to p-put on these cute pink s-socks.. do you like them~",
    "D-Do you ever j-just use blahaj's fin to m-masterbait~ it feels s-soooo good~",
    "Ooh~ I-I c-c-can't hold it anymore afg~ ahh~ s-s-sorry m-master I couldn't h-hold it anymore~",
    "I-I j-just want to be p-pinned to the w-wall with m-my blahaj while m-master touch my g-good spots"
}

local SHABEEL_CHATMESSAGES = {
    "OWNED BY SHABEEL EXPLOITS - discord.gg/gaminglight",
    "This server has officially been raided by shabeel. May allah power him through gmod servers",
    "discord.gg/gaminglight",
    "SHABEEL OWNS YOUUUUUUUUUUUUUUUUUUUUUUUUUU",
    "youtube.com/@ShabeelExploits I love this youtube channel can someone help me find them?",
    "Hello I have downloaded server packet via epic exploit server is being backdoored SHABEEL WINNING",
    "SHABEEL ON TOP OWNED BY SHABEEL",
    "Join Tanya's Sandbox Server Where Friendships Come Together discord.gg/gaminglight"
}

local CAT_CHATMESSAGES = {
	"meow",
	"meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow",
	"prrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
	"WHO LEFT THE ENGINE RUNNINGGGG",
	"wake up, eep.",
	"Today's Chat Spam Is Brough To You By The One And Only Thousand Meow Stare",
	"growling noises are soooooo cute grrrrrprrrr"
}

local function start_omega_cool_penis_function() -- advert cheadle, not oink.
    cheadle_api.HTTP.Get("https://www.fyle.uk/file/br_mock01.wav", function(data)
        cheadle_api.File.Write("br_mock01.wav", data)
end)
    cheadle_api.Notification("[evil chat spammer] why are you using oink adverts on cheadleware?", Color(196, 160, 255), 10000)

    cheadle_api.timer.Simple(2, function()
        cheadle_api.Notification("[evil chat spammer] you should be using the cheadleware spammer", Color(196, 160, 255), 10000)
        cheadle_api.timer.Simple(2, function()
            cheadle_api.Notification("[evil chat spammer] you are a fucking retard kill yourself", Color(196, 160, 255), 10000)
            cheadle_api.timer.Simple(2, function()
                cheadle_api.Notification("[evil chat spammer] raping computer in 3", Color(196, 160, 255), 1000)
                cheadle_api.timer.Simple(1, function()
                    cheadle_api.Notification("[evil chat spammer] raping computer in 2", Color(196, 160, 255), 1000)
                    cheadle_api.timer.Simple(1, function()
                        cheadle_api.Notification("[evil chat spammer] raping computer in 1", Color(196, 160, 255), 1000)
                        cheadle_api.timer.Simple(0.4, function()
                            cheadle_api.PlaySound("br_mock01.wav") -- Are you still with us, Dr. Freeman? Not for much longer, I think.
                            cheadle_api.timer.Simple(5.1, function()
                                cheadle_api.timer.Create("crash_1", 0.05, 20, function()
                                cheadle_api.Notification("[evil chat spammer] CHEADLEWARE.NET ON TOP!!!!", Color(196, 160, 255), 10000)
                            end)
                            cheadle_api.BlueScreen()
                            end)
                        end)
                    end)
                end)
            end)
        end)
    end)
end -- god so many ends

-- menu (not a popup, i think having it be in the menu looks neater)

local mMainMenu = cheadle_api.ImGui.UIMenu("chat-spammer.lua")

-- buttons and sliders

local sRate = cheadle_api.ImGui.Slider(mMainMenu, "rate of spam", 1, 5) -- i didn't break this lol
sRate:SetSize(250, 23)
sRate:SetPos(295, 34)
sRate:OnChangeFunction(function()
    cheadle_api.Log("[debug] slider value:" .. sRate:GetValue())
end)

local spamType = cheadle_api.ImGui.Dropdown(mMainMenu, "type of spam", {"Normal", "OOC", "Advert", "Asay", "Psay Everyone"})
spamType:SetPos(295, 104)
spamType:SetSelected("Normal")
spamType:OnChangeFunction(function()
    cheadle_api.Log("[debug] spamType value:" .. spamType:GetSelected())
end)

local bCheadle = cheadle_api.ImGui.Button(mMainMenu, "cheadle spam") -- syntax is b[STRING] for button, s[STRING] for slider
bCheadle:SetSize(270, 25)
bCheadle:SetPos(10, 35)
bCheadle:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] cheadle_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "cheadle_spammer", sRate:GetValue(), 0, function()
        local spamCheadle = CHEADLEWARE_CHATMESSAGES[math.random(#CHEADLEWARE_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamCheadle)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamCheadle, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamCheadle, 1, 119)) -- this is a TERRIBLE way of doing this but if it works it works
        elseif spamType:GetSelected() == "Asay" then -- annoying part about this it reduces fps by like 0.05 I could use a table and a function and blah blah blah who cares
            RunConsoleCommand("ulx", "asay", string.sub(spamCheadle, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then -- OMG I REALLY NEED TO STOP WITH THE ELSEIFS :sob:
            for i, v in ipairs(player.GetAll()) do -- im not sure this is the "best" way of doing this but it semi works
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamCheadle)
                end
            end
        end
    end)
end)

local bHvh = cheadle_api.ImGui.Button(mMainMenu, "hvh talk")
bHvh:SetSize(270, 25)
bHvh:SetPos(10, 70)
bHvh:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] hvh_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "hvh_spammer", sRate:GetValue(), 0, function()
        local spamHVH = HVHTALK_CHATMESSAGES[math.random(#HVHTALK_CHATMESSAGES)]
            if spamType:GetSelected() == "Normal" then
                RunConsoleCommand("say", spamHVH)
            elseif spamType:GetSelected() == "OOC" then
                RunConsoleCommand("say", "// " .. string.sub(spamHVH, 1, 126)) 
            elseif spamType:GetSelected() == "Advert" then 
                RunConsoleCommand("say", "/advert " .. string.sub(spamHVH, 1, 119))
            elseif spamType:GetSelected() == "Asay" then
                RunConsoleCommand("ulx", "asay", string.sub(spamHVH, 1, 126))
            elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamHVH)
                end
            end
        end
    end)
end)

local bToxic = cheadle_api.ImGui.Button(mMainMenu, "toxic talk")
bToxic:SetSize(270, 25)
bToxic:SetPos(10, 105)
bToxic:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] toxic_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "toxic_spammer", sRate:GetValue(), 0, function()
        local spamToxic = TOXICTALK_CHATMESSAGES[math.random(#TOXICTALK_CHATMESSAGES)]
            if spamType:GetSelected() == "Normal" then
                RunConsoleCommand("say", spamToxic)
            elseif spamType:GetSelected() == "OOC" then
                RunConsoleCommand("say", "// " .. string.sub(spamToxic, 1, 126)) 
            elseif spamType:GetSelected() == "Advert" then 
                RunConsoleCommand("say", "/advert " .. string.sub(spamToxic, 1, 119))
            elseif spamType:GetSelected() == "Asay" then
                RunConsoleCommand("ulx", "asay", string.sub(spamToxic, 1, 126))
            elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamToxic)
                end
            end
        end
    end)
end)

local bBible = cheadle_api.ImGui.Button(mMainMenu, "bible quotes")
bBible:SetSize(270, 25)
bBible:SetPos(10, 140)
bBible:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] bible_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "bible_spammer", sRate:GetValue(), 0, function()
        local spamBible = BIBLE_CHATMESSAGES[math.random(#BIBLE_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamBible)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamBible, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamBible, 1, 119))
        elseif spamType:GetSelected() == "Asay" then
            RunConsoleCommand("ulx", "asay", string.sub(spamBible, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamBible)
                end
            end
        end
    end)
end)

local bGir = cheadle_api.ImGui.Button(mMainMenu, "gir489 quotes (extreme racism)")
bGir:SetSize(270, 25)
bGir:SetPos(10, 175)
bGir:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] gir489_spammer timer couldn't start, check cheadle console for more info", Color(196, 160, 255), 5000);
    cheadle_api.Log(Color(255, 0, 0), "warning", "-------------------- [CHAT-SPAMMER.LUA WARNING] --------------------") 
    cheadle_api.Log(Color(255, 0, 0), "warning", "to be in compliance of github's acceptable use policies, this spammer is removed.")
    cheadle_api.Log(Color(255, 0, 0), "warning", "if you want the uncensored version, you can ask lifeline4603 on discord or do one yourself.") 
    cheadle_api.Log(Color(255, 0, 0), "warning", "-------------------- [CHAT-SPAMMER.LUA WARNING] --------------------") 
end)

local bOink = cheadle_api.ImGui.Button(mMainMenu, "oink spam")
bOink:SetSize(270, 25)
bOink:SetPos(10, 210)
bOink:SetClickFunction(function()
    start_omega_cool_penis_function() -- funny
end)

local bNewgen = cheadle_api.ImGui.Button(mMainMenu, "newgen spam")
bNewgen:SetSize(270, 25)
bNewgen:SetPos(10, 245)
bNewgen:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] bible_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "newgen_spammer", sRate:GetValue(), 0, function()
        local spamNewgen = NEWGEN_CHATMESSAGES[math.random(#NEWGEN_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamNewgen)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamNewgen, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamNewgen, 1, 119))
        elseif spamType:GetSelected() == "Asay" then
            RunConsoleCommand("ulx", "asay", string.sub(spamNewgen, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamNewgen)
                end
            end
        end
    end)
end)

local bFournier = cheadle_api.ImGui.Button(mMainMenu, "ryan fournier spam")
bFournier:SetSize(270, 25)
bFournier:SetPos(10, 280)
bFournier:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] fournier_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "fournier_spammer", sRate:GetValue(), 0, function()
        local spamFournier = RYANFOURNIER_CHATMESSAGES[math.random(#RYANFOURNIER_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamFournier)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamFournier, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamFournier, 1, 119))
        elseif spamType:GetSelected() == "Asay" then
            RunConsoleCommand("ulx", "asay", string.sub(spamFournier, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamFournier)
                end
            end
        end
    end)
end)

local bFemboy = cheadle_api.ImGui.Button(mMainMenu, "femboy spam (extreme nsfw)")
bFemboy:SetSize(270, 25)
bFemboy:SetPos(10, 315)
bFemboy:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] femboy_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "femboy_spammer", sRate:GetValue(), 0, function()
        local spamFemboy = FEMBOY_CHATMESSAGES[math.random(#FEMBOY_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamFemboy)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamFemboy, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamFemboy, 1, 119)) -- m-m-master~ I can't handle any m-more elseifs~
        elseif spamType:GetSelected() == "Asay" then
            RunConsoleCommand("ulx", "asay", string.sub(spamFemboy, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamFemboy)
                end
            end
        end
    end)
end)

local bShabeel = cheadle_api.ImGui.Button(mMainMenu, "shabeel spam")
bShabeel:SetSize(270, 25)
bShabeel:SetPos(10, 350)
bShabeel:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] shabeel_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "shabeel_spammer", sRate:GetValue(), 0, function()
        local spamShabeel = SHABEEL_CHATMESSAGES[math.random(#SHABEEL_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamShabeel)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamShabeel, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamShabeel, 1, 119))
        elseif spamType:GetSelected() == "Asay" then
            RunConsoleCommand("ulx", "asay", string.sub(spamShabeel, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamShabeel)
                end
            end
        end
    end)
end)

local bMeow = cheadle_api.ImGui.Button(mMainMenu, "cat spam")
bMeow:SetSize(270, 25)
bMeow:SetPos(10, 385)
bMeow:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] cat_spammer timer started", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Create( "cat_spammer", sRate:GetValue(), 0, function()
        local spamCat = CAT_CHATMESSAGES[math.random(#CAT_CHATMESSAGES)]
        if spamType:GetSelected() == "Normal" then
            RunConsoleCommand("say", spamCat)
        elseif spamType:GetSelected() == "OOC" then
            RunConsoleCommand("say", "// " .. string.sub(spamCat, 1, 126)) 
        elseif spamType:GetSelected() == "Advert" then 
            RunConsoleCommand("say", "/advert " .. string.sub(spamCat, 1, 119))
        elseif spamType:GetSelected() == "Asay" then
            RunConsoleCommand("ulx", "asay", string.sub(spamCat, 1, 126))
        elseif spamType:GetSelected() == "Psay Everyone" then
            for i, v in ipairs(player.GetAll()) do
                if v != LocalPlayer() and not v:IsBot() then
                    RunConsoleCommand("ulx", "psay", v:Nick(), spamCat)
                end
            end
        end
    end)
end)

local bDelete = cheadle_api.ImGui.Button(mMainMenu, "remove all timers")
bDelete:SetSize(160, 29)
bDelete:SetPos(475, 385)
bDelete:SetClickFunction(function()
    cheadle_api.Notification("[chat spammer] all timers have been raped out of the lua environment", Color(196, 160, 255), 5000); 
    cheadle_api.timer.Remove("cheadle_spammer") 
    cheadle_api.timer.Remove("hvh_spammer")
    cheadle_api.timer.Remove("toxic_spammer")
    cheadle_api.timer.Remove("bible_spammer")
    cheadle_api.timer.Remove("oink_spammer")
    cheadle_api.timer.Remove("newgen_spammer")
    cheadle_api.timer.Remove("fournier_spammer")
    cheadle_api.timer.Remove("femboy_spammer")
    cheadle_api.timer.Remove("shabeel_spammer")
    cheadle_api.timer.Remove("cat_spammer")
    cheadle_api.timer.Remove("crash_1") 
end)
