-- notes
-- ooc spam is not here, dont care to add it (unless mr shiba the femboy wants to add it, i MIGHT give you a sub extend if you do (maybe))

-- messages

local OINK_CHATMESSAGES = {
    "OINK.INDUSTRIES ON TOP, USE OINK.INDUSTRIES!",
    "Today's Killing Spree Is Sponsored By Oink.Industries!",
    "owned by oink. buy oink at oink.industries",
    "OINK OINK OINK OINK OINK OINK OINK OINK",
    "40 per year, 12 per month. cheap price for extra skill.",
    "chat is he using oink.industries?",
	"oink.industries - leading the cheating scene in 2023.",
	"you can buy a better cheat at oink.industries"
}

local HVHTALK_CHATMESSAGES = {
	"ur literally dog shit at this game!!!!!!",
	"nn dog? nn dog? nn dog? nn dog? nn dog? nn dog? ",
	[["why am i missing so much?!?!?!?!?" no fake angles in 2k23????]],
	"you can buy a better cheat at oink.industries",
	"im winning too much bro. change up ur settings so u can beat me!!!!!!!!!",
	"using idiotbox?",
	"is ur nospread and norecoil working???",
	"nice aa retard lmao",
	"DID YOU SEE THAT BACKTRACK RIGHT THERE???"
}

local TOXICTALK_CHATMESSAGES = {
	"HOLY SHIT YALL ARE HORRIBLE WTF",
	"MY KD IS SO MUCH BETTER THAN YOURS LOOOOOOOL",
	"YOU WANT TO 1V1 KID? ILL SLAP YOU LIKE YOUR MOTHER",
	"EZZZZZZZZZZZZZZZZZ EZZZZZZZZZZZZZ NO OINK NO TALK",
	[["YO WHAT CHEAT IS THAT WHAT CHEAT" OINK.INDUSTRIES ON TOPPPP]],
	"crash! poof! gone! vaporized! destroyed!",
	"lol you literally got owned by a child.",
	"I WILL DOMINATE YOU BECAUSE IM YOUR MASTER, KITTEN...",
	"HAHAHAHHAHAH OWNEDDDDDDDDDDDDDDDDD",
	"FEELS LIKE TACOBOT.TF. IN REALITY, IM JUST BETTER."
}

local BIBLE_CHATMESSAGES = {
	[["Ask and it will be given to you." - Jesus (Matthew 7:7)]],
	[["Faith can move mountains." - Jesus (Matthew 17:20)]],
	[["I am the way, the truth, and the life." - Jesus (John 14:6)]],
	[["Cast your cares on the Lord." - David (Psalm 55:22)]],
	[["Seek and you will find." - Jesus (Matthew 7:7)]],
	[["The Lord is my light and salvation." - David (Psalm 27:1)]],
	[["Love covers a multitude of sins." - Peter (1 Peter 4:8)]],
	[["Do not worry, for I am with you." - Isaiah (Isaiah 41:10)]],
	[["A soft answer turns away wrath." - Solomon (Proverbs 15:1)]],
	[["Trust in the Lord with all your heart." - Solomon (Proverbs 3:5)]],
	[["I can do everything through Him." - Paul (Philippians 4:13)]],
	[["He heals the brokenhearted." - David (Psalm 147:3)]],
	[["The word of God is living and active." - Paul (Hebrews 4:12)]],
	[["Give thanks in all circumstances." - Paul (1 Thessalonians 5:18)]],
	[["The Lord will fight for you." - Moses (Exodus 14:14)]]
}
	
local CHEADLEWARE_CHATMESSAGES = {
    "Cheadleware on top! Buy now on cheadleware.net",
    "she cheadle on my software whilst spy caming on them hoes with screengrab proof visuals",
    "This server has been backdoored by cheadleware. Please be scared I need attention",
    "UKRAINE PIG OWNS YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "Cheadleware merch coming soon!",
    "BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE BUY CHEADLEWARE",
    "Did you know you can buy cheadleware for 40 dollars only? It's lifetime too. It's kinda crazy...",
    "https://i.imgur.com/lIa2bkE.png cheadlware cake looks so good. you want a slice?",
    "cheadleware.net",
    "cheadleware.net cheadleware.net cheadleware.net cheadleware.net cheadleware.net cheadleware.net cheadleware.net"
}

local NEWGEN_CHATMESSAGES = {
    "Skibidi Dop Dop Dop Yes Yes? Skibidi Dopolo Diep Diep?",
    "Sticking Out Your Gyat For The Rizzler, You're So Skibidi, So Fanum Tax.",
    "OH MY GOOWDDDDDDD LOOK AT THAT GYATTTTTTT",
    "PLEASE NO PROTECT ME FROM THE CAMERAMEN THEY ATTACK ME AND FAMILY OF SKIBIDI TOILETS HELP MEEEEEEEEE",
    "SKIBIDI OWNS YOUR SERVER AND GM_BIGCITY. YOU HAVE NO ESCAPE MUAHAHAHAHAHAHHAHAHHAHHAHAHHHAAAAAA",
    "I just wanna be your sigma, Freaking come here, Give me your ohio.",
    "You're not a sigma male like me. You're a fat loser. Escape the matrix with hustlers university 2.0...",
    "That's so fruity uwu",
    "Did it hurt? When you fell out of heaven? Generated by RizzApp.io",
    "ULTIMATE RIZZ LOADING... 5%... 30%... 70%... 99%... ERROR, SKIBIDI TOILET HACKER DETECTED DEFENDING ATTACK!!!",
    "womp womp"
}

local RYANFOURNIER_CHATMESSAGES = {
    "Your server has been backdoored by evil ryan fournier. Changing level to prometheus_berlin_v2...",
    "Evil Ryan Fournier has access to your computer. Your firewall has been jumped. Say goodbye to your files...",
    "IM GONNA PISTOL WHIP THE SHIT OUT OF YOU HAHAHAHAHAHAHAHAHAHAHAH",
    "Students4Trump Sponsors this daily segment of raping garry's mod servers. Please donate to our ORG.",
    "My wife was my first target, this server is my second target. *he grips his gun harder and harder*",
    "Injecting evil_ryan_fournier_backdoor_services_dll_main_application.exe into server code...",
    "RATTED BY EVILRYANFOURNIER! evilryanfournier.com!"
}

local FEMBOY_CHATMESSAGES = {
    "h-hey. I'm a small little femboy. D-do you want to co-orrupt me? I'm a si-ssy femboy.",
    "I'm into tall and big guys so they can hold me and tell me how much of a good boy I am...",
    "p-p-PLEASE MAASTER GI-IIIVE ME MO-RE O-OF THAT *moaning*",
    "I'm my master's little s-slut. He can do whatever he wants to me and my b-b-body...",
    "I have my vibrator set to low as we speak... I-it feels so go-oood",
    "Master here. My helpless little slut here is such a good girl... He always begs for more like a good soul...",
    "Being a submissive little femboy slut feels so good. I like not having rights.",
    "You can p-pinch and twist both of my nipples. They're very sensitive and round.",
    "I remember when I was t-ied up for hours with a dildo pumping into me. My a-ass has never been the same...",
    "I'm the #385923th cumdump in the world. You can use me for free uwu.",
    "P-Please DM me on discord. My name is 'iamleigh_'. E-Dating Prices are 5-10€ an hour."
}

local SHABEEL_CHATMESSAGES = {
    "OWNED BY SHABEEL EXPLOITS - discord.gg/gaminglight",
    "This server has officially been raided by shabeel. May allah power him through gmod servers",
    "discord.gg/gaminglight",
    "SHABEEL OWNS YOUUUUUUUUUUUUUUUUUUUUUUUUUU",
    "youtube.com/@ShabeelExploits I love this youtube channel can someone help me find them?",
    "Hello I have downloaded server packet via epic exploit server is being backdoored SHABEEL WINNING",
    "SHABEEL ON TOP OWNED BY SHABEEL"
}

local CAT_CHATMESSAGES = {
	"meow",
	"meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow",
	"prrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
	"WHO LEFT THE ENGINE RUNNINGGGG",
	"wake up, eep.",
	"Today's Chat Spam Is Brough To You By The One And Only Thousand Meow Stare",
	"growling noises are soooooo cute grrrrrprrrr"
}

local CUSTOM_CHATMESSAGES = { -- replace with whatever
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here",
	"replace with custom message here"
}


-- part one of context details

secret.create_groupbox("misc", "right", "chat spammer", 490)

secret.create_slider("misc", "chat spammer", "rate (seconds)", 1, 5, "sRate")

local sliderRate = secret.config_get("sRate")

	local function bOinkSpam()
		timer.Create( "oink_spammer", sliderRate, 0, function()
			local spamOink = OINK_CHATMESSAGES[math.random(#OINK_CHATMESSAGES)]
			RunConsoleCommand("say", spamOink)
			
		end)
	end

	local function bHvhSpam()
		timer.Create( "hvh_spammer", sliderRate, 0, function()
			local spamHVH = HVHTALK_CHATMESSAGES[math.random(#HVHTALK_CHATMESSAGES)]
			RunConsoleCommand("say", spamHVH)
			
		end)
	end

	local function bToxicSpam()
		timer.Create( "toxic_spammer", sliderRate, 0, function()
			local spamToxic = TOXICTALK_CHATMESSAGES[math.random(#TOXICTALK_CHATMESSAGES)]
			RunConsoleCommand("say", spamToxic)
			
		end)
	end

	local function bBibleSpam()
		timer.Create( "bible_spammer", sliderRate, 0, function()
			local spamBible = BIBLE_CHATMESSAGES[math.random(#BIBLE_CHATMESSAGES)]
			RunConsoleCommand("say", spamBible)
			
		end)
	end

	local function bGirSpam()
        secret.notify("gir489_spammer timer couldn't start. check secret console for more info", 2)
        secret.log("[chat-spammer.lua] to be in compliance of github's acceptable use policies, this spammer is removed.", 1, true)
        secret.log("[chat-spammer.lua] if you want the uncensored version, you can ask lifeline4603 on discord or do one yourself.", 1, true)
	end

    local function bCheadleSpam()
		timer.Create( "cheadle_spammer", sliderRate, 0, function()
			local spamCheadle = CHEADLEWARE_CHATMESSAGES[math.random(#CHEADLEWARE_CHATMESSAGES)]
			RunConsoleCommand("say", spamCheadle)
			
		end)
	end

	local function bNewgenSpam()
		timer.Create( "newgen_spammer", sliderRate, 0, function()
			local spamNewgen = NEWGEN_CHATMESSAGES[math.random(#NEWGEN_CHATMESSAGES)]
			RunConsoleCommand("say", spamNewgen)
			
		end)
	end

	local function bFournierSpam()
		timer.Create( "fournier_spammer", sliderRate, 0, function()
			local spamFournier = RYANFOURNIER_CHATMESSAGES[math.random(#RYANFOURNIER_CHATMESSAGES)]
			RunConsoleCommand("say", spamFournier)
			
		end)
	end

	local function bFemboySpam()
		timer.Create( "femboy_spammer", sliderRate, 0, function()
			local spamFemboy = FEMBOY_CHATMESSAGES[math.random(#FEMBOY_CHATMESSAGES)]
			RunConsoleCommand("say", spamFemboy)
			
		end)
	end

	local function bShabeelSpam()
		timer.Create( "shabeel_spammer", sliderRate, 0, function()
			local spamShabeel = SHABEEL_CHATMESSAGES[math.random(#SHABEEL_CHATMESSAGES)]
			RunConsoleCommand("say", spamShabeel)
			
		end)
	end

	local function bMeowSpam()
		timer.Create( "cat_spammer", sliderRate, 0, function()
			local spamCat = CAT_CHATMESSAGES[math.random(#CAT_CHATMESSAGES)]
			RunConsoleCommand("say", spamCat)
			
		end)
	end

	local function bCustomSpam()
		secret.log("replace anything in the CUSTOM_CHATMESSAGES table within the code!", 3)
        secret.notify("check secret console for instructions", 0)
		timer.Create( "custom_spammer", sliderRate, 0, function()
			local spamCustom = CUSTOM_CHATMESSAGES[math.random(#CUSTOM_CHATMESSAGES)]
			RunConsoleCommand("say", spamCustom)
			
		end)
	end

	local function bRemove()
		timer.Remove( "oink_spammer" )
		timer.Remove( "hvh_spammer" )
		timer.Remove( "toxic_spammer" )
		timer.Remove( "bible_spammer" )
		timer.Remove( "custom_spammer" )
		timer.Remove( "cheadle_spammer" )
		timer.Remove( "newgen_spammer" )
		timer.Remove( "fournier_spammer" )
		timer.Remove( "femboy_spammer" ) -- femboy_spammer
		timer.Remove( "shabeel_spammer" )
		timer.Remove( "cat_spammer" )
	end

	secret.create_button("misc", "chat spammer", "oink spam/advert", bOinkSpam) -- we do buttons because i couldn't get checkboxes to work with timers
	secret.create_button("misc", "chat spammer", "hvh talk", bHvhSpam)
	secret.create_button("misc", "chat spammer", "toxic talk", bToxicSpam)
	secret.create_button("misc", "chat spammer", "bible quotes", bBibleSpam)
	secret.create_button("misc", "chat spammer", "gir489 quotes (extreme racism)", bGirSpam)
	secret.create_button("misc", "chat spammer", "cheadle spam", bCheadleSpam)
	secret.create_button("misc", "chat spammer", "newgen spam", bNewgenSpam)
	secret.create_button("misc", "chat spammer", "ryan fournier spam", bFournierSpam)
	secret.create_button("misc", "chat spammer", "femboy spam (extreme nsfw)", bFemboySpam)
	secret.create_button("misc", "chat spammer", "shabeel spam", bShabeelSpam)
	secret.create_button("misc", "chat spammer", "cat spam", bMeowSpam)
	secret.create_button("misc", "chat spammer", "custom spam", bCustomSpam)
	secret.create_button("misc", "chat spammer", "destroy all timers", bRemove)

